config/routes.rb
Rails.application.routes.draw do
  get 'notifications', to: 'notifications#index'
  get 'books/new'
  get 'books/edit'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
	root 'static_pages#home'
  get 'static_pages/home'
  get 'signup', to: 'users#new'
  post 'signup',  to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search', to: 'searches#index'
  get 'advanced_search', to: 'searches#new'
  post 'advanced_search', to: 'searches#create'
  patch 'approve', to: 'borrowings#approve'
  delete 'deny', to: 'borrowings#deny'
  delete 'return', to: 'borrowings#return'
  post 'find', to: 'borrowings#find'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :books
  resources :borrowings, only: [:create, :edit, :update, :destroy, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :activation_token, :reset_token
	has_many :borrowings, dependent: :destroy
	has_many :notifications, dependent: :destroy
	before_save :downcase_email
	before_create :create_activation_digest
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
		format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :role, presence: true, format: { with: /(librarian|user)/i }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	validates :number_of_borrowed_books, numericality: { less_than: 6,
		greater_than_or_equal_to: 0 }

	def User.digest string
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
																									BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def activate
		update_attribute(:activated, true)
		update_attribute(:activated_at, Time.zone.now)
	end

	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	def create_reset_digest
		self.reset_token = User.new_token
		update_attribute(:reset_digest, User.digest(reset_token))
		update_attribute(:reset_sent_at, Time.zone.now)
	end

	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end

	def password_reset_expired?
		reset_sent_at < 2.hours.ago
	end

	def librarian?
		self.role == "librarian"
	end

	private

		def downcase_email
			self.email = email.downcase
		end

		def create_activation_digest
			self.activation_token = User.new_token
			self.activation_digest = User.digest(activation_token)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:index, :edit, :update]
	before_action :correct_user, only: [:edit, :update]

	def index
		@users = User.paginate(page: params[:page])
	end

	def show
		@user = User.find(params[:id])
	end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.role = "user"
    if @user.save
    	@user.send_activation_email
    	flash[:info] = "Please check your email for account activation"
      redirect_to login_path
    else
      render 'new'
    end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  		flash[:success] = "Profile updated"
  		redirect_to @user
  	else
  		render 'edit'
  	end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, 
      	:password_confirmation, :birthday, :address)
    end

    def logged_in_user
    	unless logged_in?
    		store_location
    		flash[:danger] = "Please log in to continue"
    		redirect_to login_url
    	end
    end

    def correct_user
    	@user = User.find(params[:id])
    	redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/users_helper.rb
module UsersHelper

    # Returns the Gravatar (http://gravatar.com/) for the given user.
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end

end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :birthday %>
      <%= f.date_field :birthday, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>  

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :birthday %>
      <%= f.date_field :birthday %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %><br>
      </h1>
      <h2>
        <span class="label label-success">Email</span> <%= @user.email %><br>
        <span class="label label-success">Birthday</span> <%= @user.birthday unless @user.birthday.nil? %><br>
        <span class="label label-success">Address</span> <%= @user.address unless @user.address.nil? %><br>
      </h2>
    </section>
  </div>
  <% if @user.librarian? %>
    <div class="librarian-control">
      <%= link_to "Add new book", new_book_path %><br>
      <%= link_to "Show all borrowings", borrowings_path %><br>
      <%= link_to "Show all requests", root_path %><br>
    </div>
  <% end %>
</div>