config/routes.rb
Rails.application.routes.draw do
  get 'notifications', to: 'notifications#index'
  get 'books/new'
  get 'books/edit'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
	root 'static_pages#home'
  get 'static_pages/home'
  get 'signup', to: 'users#new'
  post 'signup',  to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search', to: 'searches#index'
  get 'advanced_search', to: 'searches#new'
  post 'advanced_search', to: 'searches#create'
  patch 'approve', to: 'borrowings#approve'
  delete 'deny', to: 'borrowings#deny'
  delete 'return', to: 'borrowings#return'
  post 'find', to: 'borrowings#find'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :books
  resources :borrowings, only: [:create, :edit, :update, :destroy, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	validates :name, presence: true, length: { maximum: 50 }
	validates :author, presence: true, length: { maximum: 50 }
	validates :pages, presence: true
	validates :publisher, presence: true, length: { maximum: 50 }
	validates :publication_date, presence: true
	validates :availability, presence: true
	validates :dewey_code, presence: true, numericality: { less_than: 9999 }
	has_many :borrowings, dependent: :destroy

	def self.search(params)
		if params
			@books = Book.where("name like ?", "%#{params}%")
		else
			Book.all
		end
	end

	def self.advanced_search(search)
		@books = Book.where(search)
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :valid_user, only: [:new, :edit]

	def index
		@books = Book.search(params[:search]).paginate(page: params[:page], per_page: 10)
    flash.now[:info] = "No books found" if @books.empty?
    respond_to do |format|
      format.html
      format.js
    end
	end

	def show
		@book = Book.find(params[:id])
    @borrowings = @book.borrowings
    session[:book_id] = @book.id
	end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
    @book.genre = Dewey.get_genre(@book.dewey_code)
  	if @book.save
  		flash[:info] = "Book added."
  		redirect_to @book
  	else
  		render 'new'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update_attributes(book_params)
      @book.genre = Dewey.get_genre(@book.dewey_code)
      @book.save
  		flash[:success] = "Book updated"
  		redirect_to @book
  	else
  		render 'edit'
  	end
  end

  private

  	def valid_user
  		@user = current_user
  		unless @user.role == "librarian"
  			flash[:danger] = "You have no right for this function."
  			redirect_to root_url
  		end
  	end

  	def book_params
      params.require(:book).permit(:name, :author, :dewey_code,
      	:publisher, :publication_date, :pages, :availability, :description)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<tr id="book-content">
	<th class="book-content"><%= link_to book.name, book %></th>
  <th class="book-content"><%= book.author %></th>
  <th class="book-content"><%= book.genre %></th>
  <th class="book-content"><%= book.publisher %></th>
  <th class="book-content"><%= book.publication_date.strftime("%b %e %Y") %></th>
  <th class="book-content"><%= book.pages %></th>
  <th class="book-content"><%= book.availability %></th>
</tr>

app/views/books/_borrow.html.erb
<%= form_for(current_user.borrowings.build) do |f| %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= hidden_field_tag :book_id, current_book.id %>
  <%= f.submit "Borrow", class: "btn btn-primary borrow-button" %>
<% end %>

app/views/books/_cancel.html.erb
<%= form_for(current_user.borrowings.find_by(user_id: current_user.id, book_id: @book.id), html: { method: :delete }) do |f| %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= hidden_field_tag :book_id, current_book.id %>
  <%= f.submit "Cancel", class: "btn cancel-button" %>
<% end %>

app/views/books/_extend.html.erb
<%= form_for(current_user.borrowings.find_by(user_id: current_user.id, book_id: current_book.id), html: { method: :patch }, remote: true) do |f| %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= hidden_field_tag :book_id, current_book.id %>
  <%= f.label :borrow_more %> (days)
  <input type="text" name="extension_day">
  <%= f.submit "Extend", class: "btn" %>
<% end %>

app/views/books/edit.html.erb
<% provide(:title, 'Edit book') %>
<h1>Edit Book</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :author %>
      <%= f.email_field :author, class: 'form-control' %>

      <%= f.label :dewey_code %>
      <%= f.text_field :dewey_code, class: 'form-control' %>

      <%= f.label :publisher %>
      <%= f.text_field :publisher, class: 'form-control' %>

      <%= f.label :publication_date %>
      <%= f.date_field :publication_date, class: 'form-control' %>

      <%= f.label :pages %>
      <%= f.text_field :pages, class: 'form-control' %>

      <%= f.label :availability %>
      <%= f.text_field :availability, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>

      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<% provide(:title, 'All books') %>
<hr>
<% if current_user %>
	<% if current_user.librarian? %>
		<%= link_to "Add new book", new_book_path, class: 'btn btn-primary' %>
	<% end %>
<% end %>
<%= form_tag("/books", method: "get", remote: true, class: "books-search") do %>
	<%= text_field_tag :search, nil, placeholder: "Search...", id: "search-bar" %>
	<%= submit_tag "Search", id: "search-button", class: "btn btn-info" %>
<% end %>
<a href="/advanced_search">Advanced Search</a><br>

<hr>

<div class="table-responsive">
	<table class="table table-striped" id="books-table">
		<tr id="table-header">
			<th><strong>Title</strong></th>
			<th><strong>Author</strong></th>
			<th><strong>Genres</strong></th>
			<th><strong>Publisher</strong></th>
			<th><strong>Publication Date</strong></th>
			<th><strong>Num. of pages</strong></th>
			<th><strong>Availability</strong></th>
		</tr>
		<tbody class="books">
			<%= render @books %>
		</tbody>
	</table>
</div>
<%= will_paginate @books, remote: true %>

app/views/books/index.js.erb
$('.books').html('<%= escape_javascript(render @books) %>');
$("div.pagination").html('<%= escape_javascript(will_paginate @books) %>');
$('.pagination a').attr('data-remote', 'true');

app/views/books/new.html.erb
<% provide(:title, 'Add new book') %>
<h1>Add new book</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>

      <%= f.label :dewey_code %>
      <%= f.number_field :dewey_code, class: 'form-control' %>

      <%= f.label :publisher %>
      <%= f.text_field :publisher, class: 'form-control' %>

      <%= f.label :publication_date %>
      <%= f.date_field :publication_date, class: 'form-control' %>

      <%= f.label :pages %>
      <%= f.number_field :pages, class: 'form-control' %>

      <%= f.label :availability %>
      <%= f.number_field :availability, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.submit "Add new book", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<% provide(:title, @book.name) %>
<div class="book-details">
  <div class="row">
    <div class="col-md-4 col-sm-4">
      <section class="book-cover">
        <div class="rectangle">
          <h2>Picture coming soon...</h2>
        </div>
      </section>
      <% if current_user %>
        <% if current_user.librarian? %>
          <section class="librarian-control">
            <%= link_to "Edit this book", edit_book_path %>
          </section>
        <% else %>
          <div id="borrow_form">
            <% if borrowing = Borrowing.find_by(user_id: current_user.id, book_id: @book.id) %>
              <% if !borrowing.verified? %>
                <%= render 'cancel' %>
              <% else %>
                <%= render 'extend' %>
              <% end %>
            <% else %>
              <% if current_book.availability > 0 %>
                <%= render 'borrow' %>
              <% else %>
                No book available
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-8 col-sm-8">
      <section class="book-info">
        <h3 class="book-detail-title"><%= @book.name %></h3>
        <h4><small>by</small> <%= @book.author %></h4>
      </section>
      <section class="col-md-6 col-sm-6">
        <span class="label label-primary">Genre</span> : <%= @book.genre %><br>
        <span class="label label-primary">Publisher</span> : <%= @book.publisher %><br>
        <span class="label label-primary">Publication Date</span> : <%= @book.publication_date.strftime("%b %e %Y") %>
      </section>
      <section class="col-md-6 col-sm-6">
        <span class="label label-primary">Number of pages</span> : <%= @book.pages %><br>
        <span class="label label-primary">Available</span> : <%= @book.availability %>
      </section>
      <section class="book-introduction">
        <p><%= @book.description.to_s %></p>
      </section>
    </div>
  </div>
</div>
<% if current_user && current_user.role == "librarian" %>
  <div class="col-sm-8 col-sm-offset-4 borrowing-status">
    <% if @borrowings.empty? %>
      <span class="label label-warning">No book borrowed</span>
    <% else %>
      <span class="label label-success">Borrower</span>
      <table class="table table-striped" id="books-table">
        <tr id="table-header">
          <th><strong>User</strong></th>
          <th><strong>Due date</strong></th>
        </tr>
        <% @borrowings.each do |i| %>
          <th><%= User.find_by(id: i.user_id).name %></th>
          <th><%= i.due_date %></th>
        <% end %>
      </table>
    <% end %>
  </div>
<% end %>