config/routes.rb
Rails.application.routes.draw do
  get 'notifications', to: 'notifications#index'
  get 'books/new'
  get 'books/edit'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
	root 'static_pages#home'
  get 'static_pages/home'
  get 'signup', to: 'users#new'
  post 'signup',  to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search', to: 'searches#index'
  get 'advanced_search', to: 'searches#new'
  post 'advanced_search', to: 'searches#create'
  patch 'approve', to: 'borrowings#approve'
  delete 'deny', to: 'borrowings#deny'
  delete 'return', to: 'borrowings#return'
  post 'find', to: 'borrowings#find'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :books
  resources :borrowings, only: [:create, :edit, :update, :destroy, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="modal fade" id="modal" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h1 class="modal-title">Log in</h1>
      </div>
      <div class="modal-body">

        <%= form_for(:session, url: login_path) do |f| %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= link_to "(forgot password)", new_password_reset_path %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :remember_me, class: "checkbox inline" do %>
            <%= f.check_box :remember_me %>
            <span>Remember me on this computer</span>
          <% end %>
          
          <%= f.submit "Log in", class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <p>New user? <%= link_to "Sign up", signup_path %></p>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-signup" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h1 class="modal-title">Sign up</h1>
      </div>
      <div class="modal-body">
        <%= form_for(:user, url: signup_path, method: "post" ) do |f| %>
          
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "Password Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>

          <%= f.label :birthday %>
          <%= f.date_field :birthday %>

          <%= f.label :address %>
          <%= f.text_field :address %>

          <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Capstone Library</a>
    by <a href="https://www.facebook.com/groups/143569486373383/">6A - Team</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">&equiv;</button>
    <%= link_to "capstone library", root_path, id: "logo", class: "navbar-brand" %>
    <nav class="collapse navbar-collapse" id="menu">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Books", books_path %></li>
        <% if logged_in? %>
          <% if current_user.role == "librarian" %>
            <li><%= link_to "Return", borrowings_path %></li>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Notifications", notifications_path %></li>
              <% if current_user.role == "librarian" %>
                <li><%= link_to "Current borrowings", borrowings_path %></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit info", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><a type="button" data-toggle="modal" data-target="#modal">Log in</a></li>
          <li><a type="button" data-toggle="modal" data-target="#modal-signup">Sign up</a></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% check_notification %>
    	<% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>